# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kopencal.ui'
#
# Created: Sat Feb 15 17:22:26 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from engine import CalcEngine

class Ui_MainWindow(object):
    def __init__(self):
        self.calc_eng = CalcEngine()
        self.flag_cleanscreen = False

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 441)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticallyt_allcontrols = QtGui.QVBoxLayout()
        self.verticallyt_allcontrols.setObjectName("verticallyt_allcontrols")
        self.txt_screen = QtGui.QLineEdit(self.centralwidget)
        self.txt_screen.setMinimumSize(QtCore.QSize(0, 41))
        self.txt_screen.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setWeight(75)
        font.setBold(True)
        self.txt_screen.setFont(font)
        self.txt_screen.setStyleSheet("color: white;\n"
"background-color:black;")
        self.txt_screen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_screen.setReadOnly(True)
        self.txt_screen.setText('0')
        self.txt_screen.setObjectName("txt_screen")
        self.verticallyt_allcontrols.addWidget(self.txt_screen)
        self.gridlyt_opsandnums = QtGui.QGridLayout()
        self.gridlyt_opsandnums.setObjectName("gridlyt_opsandnums")
        self.btn_seven = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_seven.sizePolicy().hasHeightForWidth())
        self.btn_seven.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_seven.setFont(font)
        self.btn_seven.setFlat(False)
        self.btn_seven.setObjectName("btn_seven")
        self.gridlyt_opsandnums.addWidget(self.btn_seven, 1, 0, 1, 1)
        self.btn_point = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_point.sizePolicy().hasHeightForWidth())
        self.btn_point.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_point.setFont(font)
        self.btn_point.setFlat(False)
        self.btn_point.setObjectName("btn_point")
        self.gridlyt_opsandnums.addWidget(self.btn_point, 4, 0, 1, 1)
        self.btn_product = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_product.sizePolicy().hasHeightForWidth())
        self.btn_product.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_product.setFont(font)
        self.btn_product.setFlat(False)
        self.btn_product.setObjectName("btn_product")
        self.gridlyt_opsandnums.addWidget(self.btn_product, 2, 3, 1, 1)
        self.btn_five = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_five.sizePolicy().hasHeightForWidth())
        self.btn_five.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_five.setFont(font)
        self.btn_five.setFlat(False)
        self.btn_five.setObjectName("btn_five")
        self.gridlyt_opsandnums.addWidget(self.btn_five, 2, 1, 1, 1)
        self.btn_eight = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_eight.sizePolicy().hasHeightForWidth())
        self.btn_eight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_eight.setFont(font)
        self.btn_eight.setFlat(False)
        self.btn_eight.setObjectName("btn_eight")
        self.gridlyt_opsandnums.addWidget(self.btn_eight, 1, 1, 1, 1)
        self.btn_division = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_division.sizePolicy().hasHeightForWidth())
        self.btn_division.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_division.setFont(font)
        self.btn_division.setFlat(False)
        self.btn_division.setObjectName("btn_division")
        self.gridlyt_opsandnums.addWidget(self.btn_division, 1, 3, 1, 1)
        self.btn_zero = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_zero.sizePolicy().hasHeightForWidth())
        self.btn_zero.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_zero.setFont(font)
        self.btn_zero.setFlat(False)
        self.btn_zero.setObjectName("btn_zero")
        self.gridlyt_opsandnums.addWidget(self.btn_zero, 4, 1, 1, 1)
        self.btn_four = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_four.sizePolicy().hasHeightForWidth())
        self.btn_four.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_four.setFont(font)
        self.btn_four.setFlat(False)
        self.btn_four.setObjectName("btn_four")
        self.gridlyt_opsandnums.addWidget(self.btn_four, 2, 0, 1, 1)
        self.btn_add = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add.sizePolicy().hasHeightForWidth())
        self.btn_add.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_add.setFont(font)
        self.btn_add.setFlat(False)
        self.btn_add.setObjectName("btn_add")
        self.gridlyt_opsandnums.addWidget(self.btn_add, 4, 3, 1, 1)
        self.btn_equal = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_equal.sizePolicy().hasHeightForWidth())
        self.btn_equal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_equal.setFont(font)
        self.btn_equal.setFlat(False)
        self.btn_equal.setObjectName("btn_equal")
        self.gridlyt_opsandnums.addWidget(self.btn_equal, 4, 2, 1, 1)
        self.btn_six = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_six.sizePolicy().hasHeightForWidth())
        self.btn_six.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_six.setFont(font)
        self.btn_six.setFlat(False)
        self.btn_six.setObjectName("btn_six")
        self.gridlyt_opsandnums.addWidget(self.btn_six, 2, 2, 1, 1)
        self.btn_two = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_two.sizePolicy().hasHeightForWidth())
        self.btn_two.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_two.setFont(font)
        self.btn_two.setFlat(False)
        self.btn_two.setObjectName("btn_two")
        self.gridlyt_opsandnums.addWidget(self.btn_two, 3, 1, 1, 1)
        self.btn_three = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_three.sizePolicy().hasHeightForWidth())
        self.btn_three.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_three.setFont(font)
        self.btn_three.setFlat(False)
        self.btn_three.setObjectName("btn_three")
        self.gridlyt_opsandnums.addWidget(self.btn_three, 3, 2, 1, 1)
        self.btn_subtraction = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_subtraction.sizePolicy().hasHeightForWidth())
        self.btn_subtraction.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_subtraction.setFont(font)
        self.btn_subtraction.setFlat(False)
        self.btn_subtraction.setObjectName("btn_subtraction")
        self.gridlyt_opsandnums.addWidget(self.btn_subtraction, 3, 3, 1, 1)
        self.btn_one = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_one.sizePolicy().hasHeightForWidth())
        self.btn_one.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_one.setFont(font)
        self.btn_one.setFlat(False)
        self.btn_one.setObjectName("btn_one")
        self.gridlyt_opsandnums.addWidget(self.btn_one, 3, 0, 1, 1)
        self.btn_nine = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_nine.sizePolicy().hasHeightForWidth())
        self.btn_nine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_nine.setFont(font)
        self.btn_nine.setFlat(False)
        self.btn_nine.setObjectName("btn_nine")
        self.gridlyt_opsandnums.addWidget(self.btn_nine, 1, 2, 1, 1)
        self.btn_clean = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.btn_clean.setFont(font)
        self.btn_clean.setStyleSheet("color:white;\n"
"background-color:red;")
        self.btn_clean.setObjectName("btn_clean")
        self.gridlyt_opsandnums.addWidget(self.btn_clean, 0, 3, 1, 1)
        self.verticallyt_allcontrols.addLayout(self.gridlyt_opsandnums)
        self.verticalLayout_2.addLayout(self.verticallyt_allcontrols)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #slots connections
        self.btn_zero.clicked.connect(lambda: self.pressNumOpsButton("0"))
        self.btn_one.clicked.connect(lambda: self.pressNumOpsButton("1"))
        self.btn_two.clicked.connect(lambda: self.pressNumOpsButton("2"))
        self.btn_three.clicked.connect(lambda: self.pressNumOpsButton("3"))
        self.btn_four.clicked.connect(lambda: self.pressNumOpsButton("4"))
        self.btn_five.clicked.connect(lambda: self.pressNumOpsButton("5"))
        self.btn_six.clicked.connect(lambda: self.pressNumOpsButton("6"))
        self.btn_seven.clicked.connect(lambda: self.pressNumOpsButton("7"))
        self.btn_eight.clicked.connect(lambda: self.pressNumOpsButton("8"))
        self.btn_nine.clicked.connect(lambda: self.pressNumOpsButton("9"))
        self.btn_point.clicked.connect(lambda: self.pressNumOpsButton("."))
        self.btn_equal.clicked.connect(lambda: self.pressNumOpsButton("="))
        self.btn_division.clicked.connect(lambda: self.pressNumOpsButton("/"))
        self.btn_product.clicked.connect(lambda: self.pressNumOpsButton("*"))
        self.btn_subtraction.clicked.connect(lambda: self.pressNumOpsButton("-"))
        self.btn_add.clicked.connect(lambda: self.pressNumOpsButton("+"))
        self.btn_clean.clicked.connect(lambda: self.pressNumOpsButton("C"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Kopencal", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_seven.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_point.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_product.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_five.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_eight.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_division.setText(QtGui.QApplication.translate("MainWindow", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_zero.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_four.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_equal.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_six.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_two.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_three.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_subtraction.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_one.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_nine.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clean.setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))

    #########################################################
    #                                                                  ACTIONS                                                               #
    #########################################################

    def pressNumOpsButton(self, value):
        #print self.flag_cleanscreen
        if not self.flag_cleanscreen:
            self.flag_cleanscreen = self.calc_eng.isOperator(value)
        else:
            self.flag_cleanscreen = True
            self.clearScreen

        res = None

        if value == '=':
            res = self.calc_eng.operate()
        elif value == 'C':
            self.calc_eng.cleanData()
        else:
            self.calc_eng.addSymbol(value)

        self.repaintScreen(res)

    def repaintScreen(self, res=None):
        if res:
            self.txt_screen.setText(res)
            return

        self.txt_screen.setText(self.calc_eng.getCurNumber())

    def clearScreen(self):
        self.txt_screen.setText('')


class ControlMainWindow(QtGui.QMainWindow):
    def __init__(self, parent=None):
        super(ControlMainWindow, self).__init__(parent)
        self.ui =  Ui_MainWindow()
        self.ui.setupUi(self)

